# escape=`

# use the web.config transformation base image (see \config-transform folder for details)
FROM aspnet-transform

# Copy build artiacts into container
COPY ./bin/Release/Publish/ /inetpub/wwwroot