# Use this compose file to run the app in a swarm

version: '3.3'

services:
  site:
    image: aspnet-full  # replace with the name of the image
    ports:
      - target: 80
        published: 5000
        mode: host    # host mode networking
    deploy:
        placement:
          constraints:
            - node.labels.os == windows   # place service only on Windows nodes
        endpoint_mode: dnsrr    # dns round robin load balancing
    secrets:
        - source: transform
          target: c:\transform.config

secrets:
  transform:
    external: true

# To run as a service use the following:  
# docker service create --name transform-service --publish mode=host,published=5000,target=80 --endpoint-mode dnsrr --secret src=transform,target="c:\transform.config" aspnet-full